services:
  mongo:
    image: mongo:latest
    ports:
      - "27017:27017"
    healthcheck:
      test: ["CMD", "mongosh", "--eval", "db.adminCommand('ping')"]
      interval: 10s
      timeout: 5s
      retries: 5

  fastapi:
    build:
      context: ./app
    command: uvicorn app.main:app --host 0.0.0.0 --port 8000 --reload
    env_file:
      - .env
    environment:
      - MONGODB_URL=${DATABASE_URL}
    depends_on:
      mongo:
        condition: service_healthy
    ports:
      - "8000:8000"